kowainik/relude

CHANGELOG.md
README.md
src/Universum/Nub.hs
src/Universum/Unsafe.hs

[#12] Remove liquid haskell

---

CHANGELOG.md
src/Relude/Bool/Guard.hs

Resolves #97 
Added monadic version of boolean operators.

[#97] Added monadic version of (&&) and (||) operators

---

src/Relude/Bool/Guard.hs

This PR fixes the doctests in `Relude.Bool.Guard` module.

Fix doctests in `Relude.Bool.Guard`

---

CHANGELOG.md
relude.cabal
src/Relude.hs
src/Relude/Extra/Validation.hs

Resolves #100 
Add `Validation` data type to `Extra` modules.

[#100] Add Validation data type to Extra modules

---

CHANGELOG.md
relude.cabal
src/Relude/String/Conversion.hs

Resolves #103 
Let me know if that's what you had in mind and if this change warrants a line in the CHANGELOG. If so, I'll be happy to add it.

[#103] drop utf8-string dependency

---

CHANGELOG.md
README.md
src/Relude.hs
src/Relude/Extra/Type.hs
src/Relude/Extra/Validation.hs

Prepare changelog for the 0.4.0 release [skip ci]

---

.hlint.yaml
CHANGELOG.md
hlint/hlint.dhall
src/Relude/Foldable/Fold.hs
src/Relude/Monoid.hs

Resolves #121
I didn't touch `foldMapM` for now. Probably it should be implemented using `foldMap'` from newer base.

[#121] Reexport Ap and change foldMapA

---

.hlint.yaml
CHANGELOG.md
hlint/hlint.dhall

Resolves #136
Turns out not much can be covered. We have a lot of custom things (like CallStack, newtype, Foldable1, etc.) which doesn't have analogues in `base`.

[#136] Add HLint rules for Extra modules

---

CHANGELOG.md
relude.cabal
src/Relude.hs
src/Relude/Extra/Lens.hs

[#127] Add Lens module

---

CHANGELOG.md
src/Relude/Numeric.hs

Doing geometry without atan2 makes Jack a dull boy.

Re-export `atan2` from GHC.Float

---

CHANGELOG.md
src/Relude/Extra/Validation.hs

[#172] Add Semigroup and Monoid instances to Validation

---

.hlint.yaml
CHANGELOG.md
README.md
hlint/hlint.dhall
hlint/warn.dhall
src/Relude/Container/One.hs
src/Relude/String/Conversion.hs
src/Relude/String/Reexport.hs

Resolves #164
and part of #148 
I've decided to export `toShort` and `fromShort` functions as well. I checked hoogle and it seems that there is no much functions with such names, so there should be no collisions. But let me know if it's better to not reexport them.

[#164] Reexport ShortByteString

---

CHANGELOG.md
src/Relude/Extra/Enum.hs
src/Relude/Extra/Map.hs

Use `$>` instead of `*>` and `pure` where possible

---

CHANGELOG.md
src/Relude/Foldable/Fold.hs

This is how `fmapDefault` and `foldMapDefault` look in base,
and is useful for the same reasons.

Implement `asumMap` and `foldMapA` by coercing `foldMap`

---

CHANGELOG.md
src/Relude/Extra/Enum.hs

Use `mapToFst` instead of `zip` to improve list fusion in `inverseMap`

---

CHANGELOG.md
src/Relude/Extra/Foldable1.hs

This is a big performance win.
My test program:
```haskell
{-# LANGUAGE RankNTypes, ScopedTypeVariables #-}
import Control.Monad (when)
import Data.List.NonEmpty (NonEmpty(..))
import Data.Monoid (All(..), Sum(..))
import System.Environment (getArgs)
foldMap1_old :: Semigroup m => (a -> m) -> NonEmpty a -> m
foldMap1_old f (a :| [])     = f a
foldMap1_old f (a :| b : bs) = f a <> foldMap1_old f (b :| bs)
foldMap1_new :: forall m a . Semigroup m => (a -> m) -> NonEmpty a -> m
foldMap1_new f (a :| as) = foldr go f as a
where
go :: a -> (a -> m) -> a -> m
go b g x = f x <> g b
testFoldMap1 :: (forall m a. Semigroup m => (a -> m) -> NonEmpty a -> m) -> IO ()
testFoldMap1 foldMap1 = do
print $ foldMap1 (:[]) (0 :| [1..10])
print $ foldMap1 All (True :| replicate 50000000 True)
print $ foldMap1 …
```

Implement `foldMap1` for `NonEmpty` in terms of `foldr`

---

src/Relude/Debug.hs
src/Relude/DeepSeq.hs
src/Relude/Extra/Map.hs
src/Relude/Extra/Newtype.hs
src/Relude/Extra/Validation.hs
src/Relude/File.hs
src/Relude/Function.hs
src/Relude/Lifted.hs
src/Relude/Lifted/Exit.hs
src/Relude/Lifted/File.hs
src/Relude/Lifted/IORef.hs
src/Relude/Monad/Either.hs
src/Relude/Monad/Maybe.hs
src/Relude/Monad/Trans.hs
src/Relude/Print.hs
src/Relude/Unsafe.hs

Resolves #173 
Now all tests are passing (at least on GHC-8.6.5, let's see what's CI will tell).

Documentation examples

---

hlint/hlint.dhall
hlint/warn.dhall

[#148] Migrate custom HLint rules to a newer dhall spec

---

CHANGELOG.md
src/Relude/Foldable/Reexport.hs

Resolves #192
Although there are a couple HLint rules for `foldMap`, I'm not sure if they should be copied for `foldMap'`.

Reexport foldMap' from new enough versions

---

src/Relude/List/Reexport.hs
src/Relude/String/Reexport.hs

Part of #171
Also, I did some attempts to improve errors in `head`-like functions and improve the documentation. Let me know if this is a good idea or not.

[#171] Specify custom type errors for Text functions

---

relude.cabal
test/Test/Relude/Extra/Validation/Property.hs
test/Test/Relude/Property.hs

Resolves #176 
I added property tests for basic laws of `Semigroup`/`Monoid`/`Applicative`/`Alternative`.
A copule of tests checks that `<*` and `*>` work just like default implementations in `Applicative` class.

Add property tests for the Validation type

---

CHANGELOG.md
src/Relude/Extra/Validation.hs

Return Failure early in `<*` and `*>` too

---

.travis.yml
src/Relude/DeepSeq.hs
stack.yaml

To make sure that it build with the latest Stackage snapshot and GHC-8.8.

Use latest Stackage snapshot

---

README.md

Using repeated mixins, one does not have to manually add every used `Extra` module ([docs](https://www.haskell.org/cabal/users-guide/developing-packages.html#pkg-field-mixins)).
Maybe this should also be added to the `Relude` module docs?

easier way to mixin extra modules

---

relude.cabal

When I view the package description at https://hackage.haskell.org/package/relude, this hyperlink doesn't seem to be working. I am guessing that this extra paren is the culprit.
Not related to an issue.

remove extra paren in relude.cabal description [ci skip]

---

relude.cabal

This is a redo of #247 - I only meant to correct a vowel, but I was careless and changed it to a different word entirely :) Sorry! Here's what I meant.

fix typo in relude.cabal ("unrepresentable") - attempt 2

---

README.md
src/Relude/List/NonEmpty.hs

Resolves #{none}
This is just a fix for a typo in the README file, and one typo in a comment in source code. I don't think I need to run hlint or update the CHANGELOG.

3 minor typo fixes.

---

src/Relude.hs
src/Relude/Debug.hs
src/Relude/Exception.hs
src/Relude/Extra/CallStack.hs
src/Relude/Extra/Foldable1.hs
src/Relude/Extra/Lens.hs
src/Relude/Extra/Map.hs
src/Relude/Extra/Newtype.hs
src/Relude/Extra/Validation.hs
src/Relude/Monad/Either.hs
src/Relude/Nub.hs
src/Relude/Numeric.hs
src/Relude/String.hs
src/Relude/Unsafe.hs

Resolves #{N/A}
It does not resolve any issues. Though it is related to #229.
The change in src/Relude/Extra/Lens.h was a change of an identifier name in a comment. Specifically: addressCityL had an extra 'd'
In src/Relude/Extra/CallStack.hs line 34, the spelling of an "<unknown>" in a comment was wrong. The spelling in the code was correct and was not changed. 
In src/Relude/Nub.hs, I corrected the spelling to "recommendations", and "results". Both were on the same line. 
I had to change "functions" from plural to singular in src/Relude/Extra/Newtype.hs (line 93)
I changed "if" to "is" to make a sentence grammatical in src/Relude/Extra/Validation.hs (line 167)
The rest of the changes are much simpler, and straightforward. 
- [?] I've updated the documentation accordingly.
I'm unsure what …

Correct spelling in comments.

---

src/Relude/Applicative.hs

Resolves #260
I didn't put skipci, in order to be extra careful.
- [x ] All new and existing tests pass.
- [ x ] I've used the [`stylish-haskell` file](https://github.com/kowainik/relude/blob/master/.stylish-haskell.yaml).

Delete commented out code.

---

CHANGELOG.md
hlint/hlint.dhall
src/Relude/List/Reexport.hs

Resolves #234
:warning: I could not regenerate hlint file due to issue with `dhall-to-yaml`. Though I added the new rule, so when #264 is done, these changes should be applied as well..

[#234] scan{l,r}1

---

relude.cabal
src/Relude/Container/One.hs
test/Test/Relude/Container/One.hs
test/Test/Relude/Gen.hs
test/Test/Relude/Property.hs

[#281] Move One property tests from 'doctest' to 'hedgehog' 

---

CHANGELOG.md
src/Relude/List.hs
src/Relude/List/NonEmpty.hs
src/Relude/List/Reexport.hs

Resolves #285
Reexport `NonEmpty` functions from `Relude.List.NonEmpty` instead of `Relude.List.Reexport`.

[#285] List functions Haddock Table

---

CHANGELOG.md
src/Relude/String.hs
src/Relude/String/Conversion.hs

[#286] Consistent type for 'readMaybe' and 'readEither'

---

.hlint.yaml
CHANGELOG.md
hlint/hlint.dhall
src/Relude/Lifted/IORef.hs

Resolves #294
I've also written some documentation to help navigate in this module.

[#294] Add atomicModifyIORef_ and atomicModifyIORef'_

---

src/Relude/Extra/Foldable.hs
src/Relude/Extra/Foldable1.hs

Added `average` and `average1` functions

---

CHANGELOG.md
src/Relude/List.hs

Resolves #311
Hi @chshersh! This wasn't assigned to anyone so I thought I'd give it a go, hope that was OK.
As for the naming: I didn't use one of your suggestions and came up with `maybeAt` for this but let me know if you all would prefer one of the others in the list. AFAIKT this wouldn't cause any name conflicts so just left it under `Relude.List`.

[#311] Add `maybeAt`, `!!?` with its arguments flipped

---

relude.cabal

Resolves #349. I did not update `CHANGELOG`, because it seems that it is not customary to reflect there changes of this nature (at least I do not see any such entries).

Allow bytestring-0.11

---

CHANGELOG.md
README.md
benchmark/Main.hs
src/Relude/Nub.hs
test/Test/Relude/Property.hs

Resolves #346
Benchmarks show that `intNub` is at least 2-times faster than `ordNub` (the difference is bigger on smaller lists).

[#346] Implement `ordNub` using `nubOrd` from `containers` for better efficiency

---

README.md

(Does this example actually work? Don't you have to say `Text.Show` in the instance declaration?)

"export" -> "import"

---

src/Relude/Monad/Trans.hs

Just a very small typo fix in the documentation.

[ci skip] Fix typo in author name of linked blog post

---

src/Relude/Enum.hs

The size of the map is equal to the cardinality of `a`, not `k`.

Fix warning in `inverseMap`

---

relude.cabal
src/Relude/Base.hs

Resolves #390
I left CHANGELOG untouched, because there is currently no entry for unreleased changes, and I'm not sure whether this change requires an entry: it does not change anything for existing GHCs. Happy to add an entry, if you deem it worthwhile.

Future-proof re-exports from Data.Eq

---

CHANGELOG.md
relude.cabal
src/Relude/Nub.hs

Resolves #394 
Generates a couple of warnings with `hashable-1.4`, because `Eq` is now a superclass of `Hashable`:
```
src/Relude/Nub.hs:115:1: warning: [-Wredundant-constraints]
• Redundant constraint: Eq a
• In the type signature for:
hashNub :: forall a. (Eq a, Hashable a) => [a] -> [a]
|
115 | hashNub :: forall a . (Eq a, Hashable a) => [a] -> [a]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Relude/Nub.hs:142:1: warning: [-Wredundant-constraints]
• Redundant constraint: Eq a
• In the type signature for:
unstableNub :: forall a. (Eq a, Hashable a) => [a] -> [a]
|
142 | unstableNub :: (Eq a, Hashable a) => [a] -> [a]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I can fix the type signatures with CPP if you like.

Raise upper bound on `hashable`

---

CHANGELOG.md
src/Relude/File.hs
src/Relude/Lifted/File.hs

Resolves #372
Here is an example of exceptions:
```shell
chshersh@ubuntu:~$ cat test.txt 
Привет!
chshersh@ubuntu:~$ file --mime test.txt 
test.txt: text/plain; charset=utf-8
chshersh@ubuntu:~$ LANG=en_GB.UTF-16 cabal repl -b text
Resolving dependencies...
Build profile: -w ghc-9.2.1 -O1
In order, the following will be built (use -v for more details):
- fake-package-0 (lib) (first run)
Configuring library for fake-package-0..
Preprocessing library for fake-package-0..
Warning: No exposed modules
GHCi, version 9.2.1: https://www.haskell.org/ghc/  :? for help
ghci> readFile "test.txt" 
"*** Exception: test.txt: hGetContents: invalid argument (invalid byte sequence)
ghci> import qualified Data.Text.IO as TIO
ghci> TIO.readFile "test.txt" 
*** Exception: test.txt: hGetContents: invalid …
```

[#372] Warn on usages of`readFileText` and `writeFileText`

---

CHANGELOG.md
benchmark/Main.hs
relude.cabal

Resolves #408.
I've also removed `ghc-options: -threaded -with-rtsopts=-N` from benchmark component. One is unlikely to intend running benchmarks concurrently, it's harmful for results. See https://github.com/quchen/prettyprinter/issues/197 for a similar discussion.

Switch from criterion to tasty-bench

---

src/Relude/Monad.hs

This PR fixes a small typo in the Haddock comment for `infinitely`.

fix: Fix typo in comment for `infinitely`

---

src/Relude/Nub.hs

Fix documentation typo

---

relude.cabal

Resolves #{PUT_ISSUE_NUMBER_HERE}

Allow hashable-1.5

---

.hlint.yaml
hlint/hlint.dhall

Hi @vrom911 :wave: Long-time fan of Kowainik, here's a first contribution.
I was writing something with Relude, and had a sudden brainfart failing to remember how to say `toList` :sweat_smile:
Instead I wrote `foldr (:) []` — expecting Relude's HLint ruleset to remind me a less clumsy wording — but alas, it didn't say anything! That I was shocked, says something about the quality of kowainik stuff :wink:
— :thinking:  Prolly not worth it?..

Add hlint rule, foldr (:) [] → toList
