kowainik/relude

- CHANGELOG.md
- README.md
- src/Universum.hs
- src/Universum/Container/Class.hs
- universum.cabal
> [#2] Remove microlens from dependencies

- CHANGELOG.md
- README.md
- src/Universum/Exception.hs
- universum.cabal
> [#9] Remove safe-exceptions

- .travis.yml
- src/Universum/Base.hs
- src/Universum/Container/Class.hs
- src/Universum/Debug.hs
- src/Universum/Exception.hs
- src/Universum/Foldable/Fold.hs
- src/Universum/Lifted/File.hs
- src/Universum/List/Reexport.hs
- src/Universum/List/Safe.hs
- src/Universum/Monad.hs
- src/Universum/Monad/Reexport.hs
- src/Universum/Monoid.hs
- src/Universum/String/Conversion.hs
- test/Doctest.hs
- universum.cabal
> [#6] Drop support for GHC-7.10.3

- .hlint.yaml
- CHANGELOG.md
- README.md
- src/Universum/Monad/Either.hs
- src/Universum/String/Conversion.hs
> [#16] Add, rename whenLeft* whenRight* functions

- CHANGELOG.md
- README.md
- src/Universum/Functor/Fmap.hs
- src/Universum/List/Reexport.hs
- src/Universum/String/Conversion.hs
- src/Universum/String/Reexport.hs
> [#18] Add LazyStrict type class

- CHANGELOG.md
- src/Universum/Foldable/Fold.hs
> [#17] Add foldMapA and foldMapM functions

- CHANGELOG.md
- src/Universum/Extra/Bifunctor.hs
- src/Universum/Extra/Enum.hs
- src/Universum/Extra/Group.hs
- universum.cabal
> [#14] Introduce *.Extra modules

- CHANGELOG.md
- README.md
- src/Universum/List/Safe.hs
> [#20] Add viaNonEmpty function

- CHANGELOG.md
- src/Universum/Foldable/Fold.hs
- src/Universum/Monad/Either.hs
> [#21] Add MonadFail instance for Either

- README.md
> [#15] Add instructions aboud base-noprelude

- .ghci
- .hlint.yaml
- .travis.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- benchmark/Main.hs
- relude.cabal
- src/Relude/Container.hs
- src/Relude/Extra/Group.hs
- src/Relude/Extra/Map.hs
- src/Relude/Function.hs
- test/Spec.hs
- test/Test/Relude/Property.hs
> [#5] Improve documentation

- CHANGELOG.md
- relude.cabal
- src/Relude/Extra/Enum.hs
> [#44] Derive parsers from pretty-printers

- CHANGELOG.md
- relude.cabal
- src/Relude/Extra/CallStack.hs
> [#46] Add a function that returns its own name

- CHANGELOG.md
- relude.cabal
- src/Relude/Extra/Newtype.hs
Resolves #43 
If you have any ideas of other functions, that can be added, please, don't be shy and recommend!
> [#43] Implement Relude.Extra.Newtype module

- CHANGELOG.md
- relude.cabal
- test/Test/Relude/Property.hs
> [#49] Speed up and refactor property tests

- CHANGELOG.md
- src/Relude/Functor/Fmap.hs
- src/Relude/Monad/Either.hs
> [#48] More reexports from base

- CHANGELOG.md
- src/Relude/Extra/Foldable1.hs
- src/Relude/Extra/Newtype.hs
- src/Relude/Monad/Maybe.hs
> [#41] Add `Foldable1`

- CHANGELOG.md
- README.md
- relude.cabal
- src/Relude/Debug.hs
- src/Relude/Print.hs
- src/Relude/String/Conversion.hs
> [#63] Remove Print typeclass

- .hlint.yaml
- CHANGELOG.md
- src/Relude/Function.hs
> [#66] Reexport '>>>' and '<<<'

- CHANGELOG.md
- src/Relude/Functor/Fmap.hs
> [#59] Add flap and (??)

- CHANGELOG.md
- README.md
- src/Relude/Extra/Foldable1.hs
Resolves #64 
Just couple minor improvements to existing `Foldable1`.
> [#64] Improve Foldable1 typeclass

- .hlint.yaml
- CHANGELOG.md
- README.md
- hlint/hlint.dhall
- hlint/warn.dhall
- relude.cabal
- src/Relude/Function.hs
- src/Relude/Functor/Reexport.hs
- src/Relude/Lifted/File.hs
- src/Relude/Lifted/Terminal.hs
- src/Relude/Print.hs
- src/Relude/String/Conversion.hs
> [#67] Add HLint rules for put functions

- CHANGELOG.md
- hlint/Rule.dhall
- src/Relude/Extra/Newtype.hs
- src/Relude/Foldable/Fold.hs
- src/Relude/Lifted.hs
- src/Relude/List/NonEmpty.hs
- src/Relude/Monad/Maybe.hs
- src/Relude/String/Conversion.hs
Resolves #61 
Also fixes tests and refactors some things.
> [#61] Add binary newtype combinators

- .hlint.yaml
- CHANGELOG.md
- hlint/hlint.dhall
- src/Relude/Monad/Trans.hs
> [#60] Add lifting to transformers functions

- .hlint.yaml
- CHANGELOG.md
- README.md
- hlint/hlint.dhall
- relude.cabal
- src/Relude.hs
- src/Relude/File.hs
- src/Relude/Lifted/File.hs
> [#22] Add monomorphic versions of file functions

- .travis.yml
- relude.cabal
🎉 🎉 🎉  Finally, it's possible! 🎉 🎉 🎉 
Resolves #23
> [#23] Support ghc-8.6.1

- src/Relude/Nub.hs
Resolves #83 
accordingly to my changes (add new rules for the new imports, remove old ones, when they are outdated, etc.).
[this instructions](https://github.com/kowainik/relude#generating-hlintyaml)).
with the short description of my latest changes.
[style-guide](https://github.com/kowainik/org/blob/master/style-guide.md#haskell-style-guide) 
for more details).
> [#83] Pretty latex for function asymptotics

- .hlint.yaml
- hlint/hlint.dhall
Resolves #79 
Let me know if that's what you had in mind :)
> [#79] Add hlint rules for  type class

- .hlint.yaml
- hlint/hlint.dhall
- hlint/warn.dhall
> [#117] Add hint for operators function

- CHANGELOG.md
- src/Relude/Applicative.hs
- src/Relude/Monad.hs
Sorry for taking so long!
Resolves #129 
There are some points of the checklist that I haven't done:
* Regarding `hlint`, I'm unsure whether I should add rules for this or not
* I'm not sure how to update the CHANGELOG, do I just include the changes and the PR number?
> Add appliedTo and chainedTo functions

- CHANGELOG.md
- relude.cabal
- src/Relude/Container/One.hs
Resolves :books: 
Just added docs to every instance of `One` typeclass. Also used `doctest` to write unit and property-based tests for every instance.
> Improve docs for One

- README.md
Resolves #122
I've just copy-pasted my comparison from `/r/haskell`. Should be good enough for now :)
> [#122] Add comparison with Protolude

- README.md
Resolves #123 
Open questions:
1. Should I add it to Haddock somewhere inside modules?
2. Should I swap some sections in `Get started`? Like, order them by increasing difficulty (from `NoImplicitPrelude` to mixins) or by increasing coolness (from `mixins` to `NoImplicitPrelude`)?
3. Should I add three subsections as links inside table of contents?
> [#123] Add section about mixins

- CHANGELOG.md
- src/Relude/Numeric.hs
Resolves #138
I have included all methods required to define RealFloat, as I needed them in my program.
> [#138] + RealFloat

- .hlint.yaml
- CHANGELOG.md
- hlint/hlint.dhall
- src/Relude/Extra/Tuple.hs
> [#144] Add `traverseToSnd` and friends to `Relude.Extra.Tuple`

- CHANGELOG.md
- relude.cabal
- src/Relude/Foldable/Fold.hs
> [#140] Improve compile-time error messages

- README.md
> [#134] Describe way to run relude hlint rules on CI

- .travis.yml
- CHANGELOG.md
- README.md
- relude.cabal
- src/Relude/File.hs
- src/Relude/Foldable/Fold.hs
- stack.yaml
> [#146] Improve documentation

- CHANGELOG.md
- relude.cabal
- src/Relude.hs
- src/Relude/Extra/Foldable.hs
> [#155] Add a `foldlSC` method

- .travis.yml
- README.md
- relude.cabal
- stack.yaml
- test/Doctest.hs
> [#158] Bump up to GHC-8.6.5

- relude.cabal
Resolves #{PUT_ISSUE_NUMBER_HERE}
> Typo in cabal file

- README.md
Here are a handful of suggested spelling and grammar changes to the README.
> Improve spelling and grammar

- CHANGELOG.md
- src/Relude/Lifted/Exit.hs
> Made `die` polymorphic in its return type.

- .hlint.yaml
- CHANGELOG.md
- CONTRIBUTING.md
- hlint/hlint.dhall
- src/Relude/Debug.hs
- src/Relude/Extra/Enum.hs
- src/Relude/Extra/Tuple.hs
> #167 rename (prec -> prev) &  (dupe -> dup)

- .travis.yml
- CHANGELOG.md
- relude.cabal
- src/Relude/Extra/Type.hs
- stack.yaml
Resolves #182
It's WIP currently. We're waiting for `tasty-hedgehog` to support GHC-8.8 first. But the library builds! I also updated the documentation in the `.cabal` file. It works now! Also, there's a new Haddock formatting :thinking:
> [#182] Support GHC 8.8

- CHANGELOG.md
- relude.cabal
- test/Spec.hs
- test/Test/Relude/Property.hs
> [#187] Remove tasty* dependencies

- CHANGELOG.md
- src/Relude/Extra/Bifunctor.hs
- src/Relude/Extra/Tuple.hs
> Implement `bimapBoth` (#174)

- CHANGELOG.md
- benchmark/Main.hs
- src/Relude/Bool/Guard.hs
- src/Relude/List.hs
> Implement safe `at` (!!) function

- README.md
- appveyor.yml
- src/Relude/Foldable/Fold.hs
Resolves #160 
I've stolen most of this from https://github.com/spacchetti/spago/blob/master/appveyor.yml
> Add appveyor ci

- CHANGELOG.md
- src/Relude/Bool/Guard.hs
Resolves https://github.com/kowainik/relude/issues/203
I think that I implemented it the way you want based on the type signature, but if I am wrong please let me know and I would be happy to fix it.
I am happy to write tests for this, but I couldn't see where this might fit in the `Test` folder.
Also, I am not sure how to update the documentation, I added decorated comments in the same style as the rest of the code in that file (I assume that generates haddocks).
> 203: Implement Guarded Combinator

- CHANGELOG.md
- src/Relude/Extra/Type.hs
> Implement type family Elem

- src/Relude/List/Reexport.hs
Part of #171 
Not sure if this is what needed or the error is nice or helpful...
> [#171] Add custom error to head like functions

- src/Relude/Applicative.hs
- src/Relude/Monad/Either.hs
- src/Relude/String/Conversion.hs
- src/Relude/String/Reexport.hs
Part of #171 
I also fixed some Haddock errors I introduced in my previous PR...
> [#171] Add custom type error for To* typeclasses

- CHANGELOG.md
- src/Relude/Monad/Maybe.hs
> [#214] Add `mapMaybeM`

- src/Relude/Debug.hs
- src/Relude/Extra/Foldable1.hs
- src/Relude/List/Reexport.hs
- src/Relude/String/Conversion.hs
Resolves #171
In addition, I also decided to specify more context in some other errors.
> [#171] Add custom type errors in some places

- src/Relude/Extra/Validation.hs
Resolves #221
I've also added `Monad` instance with custom type errors for `Validation` because why not if we already added a lot of such instances.
> [#221] Refactor Validation module

- CHANGELOG.md
- README.md
- src/Relude/Extra/Enum.hs
- src/Relude/Extra/Tuple.hs
> Prepare changelog for the 0.6.0.0 version

- src/Relude.hs
> docs: lement -> element

- CHANGELOG.md
- src/Relude/Extra/Lens.hs
> [#249] Fix infixity for view operator of Lens

- README.md
Thanks @argumatronic and @chris-martin for writing this helpful guide! :heart:
> Link the 'No implicit Prelude' post by Type Classes

- test/Test/Relude/Extra/Validation/Property.hs
> Rename function for better spelling of "associativity"

- CHANGELOG.md
- src/Relude/Monad/Trans.hs
> [#233] Add 'etaReaderT' function

- CHANGELOG.md
- src/Relude/Extra/Enum.hs
- src/Relude/Extra/Tuple.hs
> [#244] Remove DEPRECATED 'prec', 'dupe', 'mapBoth'

- CHANGELOG.md
- src/Relude/List/Reexport.hs
> [#256] Fix partiality in 'cycle'

- CHANGELOG.md
- src/Relude/Extra/Enum.hs
- src/Relude/Monad/Trans.hs
> [#228] Implement `universeNonEmpty`

- CHANGELOG.md
- README.md
- src/Relude.hs
- src/Relude/Extra.hs
- src/Relude/Extra/Validation.hs
> [#246] Deprecate 'Relude.Extra.Validation' in favour of validation-selective

- .hlint.yaml
- README.md
- hlint/warn.dhall
- test/Spec.hs
Resolves #264
Temporary solution: escape function `on` manually this time. Shouldn't need to do it after fix in `dhall-json`.
> [#264] Support latest Dhall spec

- README.md
- src/Relude/Bool/Guard.hs
- src/Relude/Foldable/Fold.hs
Resolves #229
I tried to fix some documentation parts I noticed.
> [#229] Minor documentation improvements: part2

- README.md
- src/Relude.hs
Special thanks to @elsanussi-s-mneina for his improvements from #259. I applied the ones that were still relevant after @chshersh changes!
> Improve README a bit more

- .hlint.yaml
- CHANGELOG.md
- hlint/hlint.dhall
- src/Relude/Extra/Enum.hs
- src/Relude/Extra/Tuple.hs
> [#196] Rename and deprecate `mapToFst/Snd`

- CHANGELOG.md
- src/Relude/Applicative.hs
- src/Relude/Bool/Guard.hs
- src/Relude/Container/One.hs
- src/Relude/Extra/Bifunctor.hs
- src/Relude/Extra/CallStack.hs
- src/Relude/Extra/Enum.hs
- src/Relude/Extra/Foldable1.hs
- src/Relude/Extra/Group.hs
- src/Relude/Extra/Lens.hs
- src/Relude/Extra/Map.hs
- src/Relude/Extra/Newtype.hs
- src/Relude/Extra/Tuple.hs
- src/Relude/Extra/Type.hs
- src/Relude/Extra/Validation.hs
- src/Relude/File.hs
- src/Relude/Foldable/Fold.hs
- src/Relude/Functor/Fmap.hs
- src/Relude/Lifted.hs
- src/Relude/Lifted/Terminal.hs
- src/Relude/List/NonEmpty.hs
- src/Relude/Monad.hs
- src/Relude/Monad/Either.hs
- src/Relude/Monad/Trans.hs
- src/Relude/Numeric.hs
- src/Relude/Print.hs
- src/Relude/String/Conversion.hs
> [#291] Archaeology Quest: add @since to EACH function

- CHANGELOG.md
- src/Relude/Monoid.hs
> [#293] Add `memptyIfTrue/False` functions

- src/Relude/Foldable/Fold.hs
Resolves #{PUT_ISSUE_NUMBER_HERE}
I think most of the checklist doesn't applies to this change, and I don't know where to add this change in `CHANGELOG.md` (I don't see any "unreleased changes" section)
> Fix name of product in haddock (was 'production')

- src/Relude/Debug.hs
> [#301] Add traceShowWith

- src/Relude/Extra/Foldable1.hs
> add foldr1 to Foldable1

- src/Relude/List.hs
> Add partitionWith function

- README.md
> [#328] Document that mixins doesn't work with stack repl

- .github/workflows/ci.yml
- README.md
- relude.cabal
> [#337] Use default main branch

- README.md
- relude.cabal
I hope it is acceptable without raising an issue first.
> Fix typo 'don not' -> 'do not'

- CHANGELOG.md
- src/Relude/Nub.hs
> [#347] Add `ordNubOn`

- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
- relude.cabal
- src/Relude/Applicative.hs
- src/Relude/Base.hs
- src/Relude/Debug.hs
- src/Relude/Exception.hs
- src/Relude/Extra/Newtype.hs
- src/Relude/Extra/Type.hs
- src/Relude/Foldable/Reexport.hs
- src/Relude/Monad/Either.hs
- src/Relude/Monad/Trans.hs
> [#268] Drop GHC 8.0.2 support

- relude.cabal
> [#280] Move to 'cabal-version: 3.0'

- CHANGELOG.md
- README.md
- relude.cabal
- src/Relude.hs
> [#353] Reexport external libraries

- benchmark/Main.hs
- relude.cabal
> [#361] Move benchmarks to criterion instead of gauge

- .github/workflows/ci.yml
- CHANGELOG.md
- relude.cabal
- src/Relude/Lifted/File.hs
- stack.yaml
> [#345] Support GHC-9.0

- README.md
Resolves https://github.com/kowainik/kowainik.github.io/issues/184
> Change relative link to hard link [ci skip]

- src/Relude/Monad/Maybe.hs
Found a couple of typos while skimming through the docs. Nothing major 😄
> Minor haddock fixes

- relude.cabal
> Support hedgehog 1.5

- src/Relude/Monad/Reexport.hs
Hopefully it gets their documentation to appear on Hackage
Resolves #472 ?
> Export MonadIO explicitly
